export type OfficialDataErrorCode =
  | "OFFICIAL_DATA_COMPOSITE_HASH_MISMATCH"
  | "OFFICIAL_DATA_COUNT_MISMATCH"
  | "OFFICIAL_DATA_DUPLICATE_SOURCE_ROW"
  | "OFFICIAL_DATA_ENRICHED_HASH_MISMATCH"
  | "OFFICIAL_DATA_HASH_MISMATCH"
  | "OFFICIAL_DATA_INTERRUPTED_GENERATION"
  | "OFFICIAL_DATA_MALFORMED_JSON"
  | "OFFICIAL_DATA_NON_CANONICAL_JSON"
  | "OFFICIAL_DATA_ORDER_MISMATCH"
  | "OFFICIAL_DATA_ROW_SCHEMA"
  | "OFFICIAL_DATA_SOURCE_MANIFEST_HASH_MISMATCH"
  | "OFFICIAL_DATA_SOURCE_MISMATCH"
  | "OFFICIAL_DATA_UNSAFE_TEXT"
  | "SOURCED_PRODUCTS_FABRICATED_ROWS"
  | "SOURCED_PRODUCTS_HASH_MISMATCH"
  | "SOURCED_PRODUCTS_LEDGER_INVALID"
  | "SOURCED_PRODUCTS_ROW_SCHEMA";

export class OfficialDataError extends Error {
  readonly name = "OfficialDataError";

  constructor(
    readonly code: OfficialDataErrorCode,
    message: string
  ) {
    super(message);
  }
}
